services:
  dovecot:
    image: codedure/dovecot
    build:
      context: app
    container_name: dovecot
    environment:
      RSPAMD_PASSWORD_ENC: $$2$$rhpb4naqycoshygfpe6b48wwejiakk3w$$zhf6bbeo4djibusp9zx7aahym8sim8dx41byyizc3kspr48wdb9y
    volumes:
      - ./config:/config
      - ./data/dovecot:/home/vmail
      - ./data/redis:/var/lib/redis
      - ./data/rspamd:/var/lib/rspamd
    ports:
      - 143:143
      - 993:993
      - 11334:11334
    restart: unless-stopped
